PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS interactables;
DROP TABLE IF EXISTS slide_transitions;
DROP TABLE IF EXISTS slides;

CREATE TABLE slides (
    slide_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    theme TEXT NOT NULL,
    tile_grid TEXT NOT NULL,
    spawn_col INTEGER NOT NULL,
    spawn_row INTEGER NOT NULL
);

CREATE TABLE slide_transitions (
    slide_id TEXT NOT NULL,
    direction TEXT NOT NULL,
    target_slide_id TEXT NOT NULL,
    target_spawn_col INTEGER NOT NULL,
    target_spawn_row INTEGER NOT NULL,
    trigger_col INTEGER NOT NULL,
    trigger_row INTEGER NOT NULL,
    PRIMARY KEY (slide_id, direction),
    FOREIGN KEY (slide_id) REFERENCES slides(slide_id) ON DELETE CASCADE,
    FOREIGN KEY (target_slide_id) REFERENCES slides(slide_id) ON DELETE CASCADE
);

CREATE TABLE interactables (
    slide_id TEXT NOT NULL,
    object_id TEXT NOT NULL,
    col INTEGER NOT NULL,
    row INTEGER NOT NULL,
    kind TEXT NOT NULL,
    properties TEXT,
    PRIMARY KEY (slide_id, object_id),
    FOREIGN KEY (slide_id) REFERENCES slides(slide_id) ON DELETE CASCADE
);

INSERT INTO slides (slide_id, name, theme, tile_grid, spawn_col, spawn_row) VALUES (
    'meadow',
    'Sunny Meadow',
    'grass',
    '....................
....................
....................
....######..........
....#....#..........
....#....#..........
....#....#..........
....######..........
....................
...........####.....
..........==========
...........#..#.....
...........####.....
....................
....................
....................
....................
....................
....................
....................',
    10,
    10
);

INSERT INTO slides (slide_id, name, theme, tile_grid, spawn_col, spawn_row) VALUES (
    'forest',
    'Shaded Grove',
    'forest',
    '####################
....................
....................
....................
....................
....................
....................
....................
....................
....................
===========.........
..........=.........
..........=.........
..........=.........
..........=.........
..........=.........
..........=.........
..........=.........
..........=.........
..........=.........',
    2,
    2
);

INSERT INTO slides (slide_id, name, theme, tile_grid, spawn_col, spawn_row) VALUES (
    'cave',
    'Crystal Cavern',
    'cave',
    '##########=#########
..........=.........
..........=.........
..........=.........
..........=.........
..........=.........
..........=.........
..........=.........
..........=.........
..........=.........
..........=.........
..........=.........
..........=.........
..........=.........
..........=.........
..........=.........
..........=.........
..........=.........
..........=.........
####################',
    5,
    15
);

INSERT INTO slide_transitions (slide_id, direction, target_slide_id, target_spawn_col, target_spawn_row, trigger_col, trigger_row) VALUES
('meadow', 'east', 'forest', 1, 10, 19, 10),
('forest', 'west', 'meadow', 18, 10, 0, 10),
('forest', 'south', 'cave', 10, 1, 10, 19),
('cave', 'north', 'forest', 10, 18, 10, 0);
